### PR TITLE
Add Appium Integration for UI Test Automation

### LINKED ISSUE #162: Proposal: Add Test Automation with Appium (Java)
Hi, I saw that the project is open to contributions, and I was wondering if it might be useful to add some Test Automation using Appium with Java. I noticed that the code is mostly written in Dart, but I’d still like to contribute by improving the automated testing part. Do you think this would be a useful direction for the project? Let me know if you think this could help!

### PR DESCRIPTION
**Pull request by raulsorrentino**
This pull request implements the proposal from [issue #162](https://github.com/emavgl/oinkoin/issues/162) to add test automation using Appium. Previously, the project did not include any automated UI tests, and this PR introduces the necessary setup to integrate Appium into the project.

### Key Features Added  
1. **Appium Configuration:**  
   - Initial setup with configuration and constants files for seamless Appium integration.  
   - Included Gradle wrapper files to ensure consistent Gradle versioning across environments.

2. **Updates to Dart Code:**  
   - Added **Semantic Identifiers** to key navigation and UI elements in the Flutter application.  
   - These identifiers enhance accessibility and ensure reliable element targeting during UI testing.

3. **Page Object Model (POM) Implementation:**  
   - Structured the pages using Page Object Model (POM) and PageFactory for maintainability.  
   - Centralized element management to simplify updates and increase code reuse.  

### Tests Added  
- **Record Management:**
  - `addExpenseRecord`: Tests adding and retrieving an expense record.
  - `addIncomeRecord`: Tests adding and retrieving an income record.
  - `deleteRecord`: Verifies that a record can be deleted successfully.
  
- **Record Visibility by Date Range:**
  - `shouldDisplayRecordsForSelectedMonthOnly`: Verifies that only records from the selected month are displayed.
  - `shouldDisplayRecordsForSelectedYearOnly`: Verifies that only records from the selected year are visible.
  - `shouldDisplayRecordsForCustomDateRangeOnly`: Verifies that only records within a custom date range are shown.

- **Date Range Filters:**  
  - `shouldDisplayCorrectTextForSelectedMonth`: Ensures that the correct date range text is displayed for the selected month.
  - `shouldDisplayCorrectTextForSelectedYear`: Ensures that the correct date range text is shown for the selected year.
  - `shouldDisplayCorrectTextForCustomDateRange`: Ensures that the correct date range text is displayed for a custom date range.
  

### Improvements and Refactoring  
- Migrated from JUnit 5 to TestNG for enhanced test setup and execution flexibility.  
- Reorganized the test structure with `@BeforeSuite` and `@AfterSuite` setup for efficiency.  
- Refactored test methods and identifiers for improved clarity and maintainability.  
- Fixed issues in assertion ordering and removed unused configurations for a cleaner codebase.

### Limitations  
Not all components of the app are covered by tests at this stage. Additional tests will be added in the future to increase test coverage, focusing on critical app components and functionality.

**Fixes #162**

### CODE REVIEW

**Comment by emavgl** [comment]
Hello, thanks for the PR and for the hard work. How are this test being executed?

**Comment by raulsorrentino** [comment]
Hello, thank you for the kind words! Here's a quick guide on how to execute these tests:

1. **Appium Server**:  
   Install [Appium](https://appium.io/docs/en/2.0/quickstart/install/) and [UiAutomator2 Driver](https://appium.io/docs/en/2.0/quickstart/uiauto2-driver/).
   Make sure the Appium server is running. You can start the server by typing `appium` in the terminal.

3. **Driver Configuration**:  
   Update the `Constants` class to match your setup:

   ```java
   public class Constants {
       public static final String PLATFORM_NAME = "Android";
       public static final String PLATFORM_VERSION = "15";   // Adjust to your device/emulator version
       public static final String UDID = "your-device-id";   // Replace with your device/emulator ID
       public static final String APP_PACKAGE = "com.github.emavgl.piggybankpro";
       public static final String APP_PATH = "/path/to/your/apk/app-pro-debug.apk"; // Update with the APK location
       public static final String APPIUM_SERVER_URL = "http://127.0.0.1:4723";      // Appium server URL
   }

5. **Device/Emulator**:  
   Connect a device or start an emulator that matches the configuration specified in the `Constants` class.

6. **Test Execution**:  
   You can run the tests either directly from your IDE (by selecting the test class or method and pressing the run button) or by using Gradle.

Let me know if you need further clarification!

**Comment by emavgl** [comment]
Just wondering, do you know if it is easy to configure it to run on GitHub actions?

**Comment by raulsorrentino** [comment]
Unfortunately, I haven’t explored configuring these tests to run on GitHub Actions yet, so I’m not sure about the specifics. It might require setting up an emulator or a device farm to execute the tests, but I’d need to research further to provide a clear answer.

**Comment by raulsorrentino** [comment]
Hello, I hope you’re doing well!

I noticed that the pull request has not been merged yet, and I see there are now new conflicts to resolve. Please let me know if there’s anything else you’d need from me to help move this forward. I’d be happy to address any additional changes or suggestions to ensure the work aligns with the project’s goals.

Regarding your earlier question about running these tests on GitHub Actions, I’ve done some preliminary research, and it seems feasible. It would likely require setting up an emulator or a device farm and integrating a CI/CD pipeline for automatic APK builds. This could be an interesting next step to explore in a future issue or pull request.

Let me know if there’s anything else you need from me. Thank you for your time and review!

**Comment by emavgl** [comment]
Hi, I am sorry I did not have time to run this on my own. While I am not fully happy to have the Widget wrapped around `Semantic` widget, I am fine with the changes in general, thanks for the work. Aas long as those tests are maintained and maybe used as quality-gate using the Github Actions, I am fine on having changes in the code.

I propose to continue this way:

1. Let's fix the conflicts
2. I'll merge this PR
3. You can investigate more if running the tests as Github Action make sense.

**Comment by emavgl** [comment]
I see https://www.linkedin.com/pulse/flutter-testing-appium-made-easy-implementing-unique-ids-element-/ it uses also attributes? Is that an option?

**Comment by raulsorrentino** [comment]
Hi, thank you for your feedback and for outlining the next steps!

Regarding the methods in the link you shared, some (e.g., `data-testid` and `AutomatedTesting.setContentDescription`) are not natively supported by Flutter. While `Key` is supported, it doesn’t translate correctly into a usable identifier for Appium (`find by`). The approach I’ve used with the `Semantics` widget is recommended by both the Flutter and Appium communities, as highlighted in the official Flutter discussion: [Flutter issue #17988](https://github.com/flutter/flutter/issues/17988).

As for wrapping widgets with `Semantics`, I understand the concern. For widgets that provide the `semanticLabel` property, we can avoid using the wrapper. For example:

**Current implementation:**

```dart
floatingActionButton: FloatingActionButton(  
    onPressed: () async => await navigateToAddNewMovementPage(),  
    tooltip: 'Add a new record'.i18n,  
    child: Semantics(  
        identifier: 'add-record',  
        child: const Icon(Icons.add),  
    ),  
),  
```

**Refactored version:**

```dart
floatingActionButton: FloatingActionButton(  
    onPressed: () async => await navigateToAddNewMovementPage(),  
    tooltip: 'Add a new record'.i18n,  
    child: const Icon(  
        Icons.add,  
        semanticLabel: 'add-record',  
    ),  
),  
```

This simplifies the widget tree, but since `semanticLabel` is only available for specific widgets, the `Semantics` widget remains the most universal and scalable approach for consistent identifier assignment.

Additionally, while the tests should still work with `semanticLabel`, identifiers will be translated into `accessibility id`/`content-desc` instead of `id`/`resource-id`.

Let me know if you’d like me to refactor the current implementation using `semanticLabel` where applicable!

**Comment by emavgl** [comment]
Hi, thank you so much for the explanation, let's keep the current implementation and maybe let's use the test for the most critical parts, so to avoid having Semantics all around the widgets :)

I'll merge it as soon as the conflicts are gone. Thanks again for your work.

**Comment by raulsorrentino** [comment]
Hi, thank you for your feedback earlier! I've resolved the conflicts, and the branch is now ready for integration. Let me know if there's anything else you'd like me to adjust.

Thanks again for your guidance and support!

**Comment by emavgl** [comment]
Merged. Thanks again! Yes, the next step for me would be trying the integration with Github Actions.

**Pull request merged**
