### PR TITLE
Archive, Emoji, Order categories

### PR DESCRIPTION
**Pull request by emavgl**
- Add emoji as icons
- Archive / Unarchive Categories
- Add Blank and White background in Category
- Add the possibility to change order of categories, most_used, last_used and custom by drag-and-drop categories
- Add metadata in Backup

Please try this out:

https://drive.google.com/drive/folders/1KGB8GDioY3Jo5HYdYaBjO53psiUO7mRg?usp=sharing

Please remember to do backup, store it somewhere and then install the new version, just to be safe.
Unfortunately, you can't install it on top of a version coming from the Google Play store or from F-droid.

### CODE REVIEW

**Comment by emavgl** [comment]
Problems found:

- When adding a new record, category icons are a bit off from the center
- Drag and drop of a category and scrolling is not easy

**Comment by emavgl** [comment]
Both fixed.

**Comment by Vertelleus** [comment]
Tested on Samsung Fold 4.
All functions appear to work as described / requested.

I will report any anomalies if they occur.

**Comment by emavgl** [comment]
Thank you! I'll release it soon

**Pull request merged**
